#!/usr/bin/python3
import numpy as np
from argparse import ArgumentParser
from matplotlib import pyplot as plt


if __name__ == "__main__":
    
    argparser = ArgumentParser()
    argparser.add_argument("file", type=str)
    argparser.add_argument("--save", action="store_true")
    argparser.add_argument("--show", action="store_true")
    args = argparser.parse_args()

    plt.figure(figsize=(6, 3))
    plt.plot(np.load(args.file), color="black")
    
    if args.save:
        plt.savefig(args.file.replace(".npy", ".png"))

    if args.show:
        plt.show()
