#!/usr/bin/python3
import pickle
from argparse import ArgumentParser


if __name__ == "__main__":
    
    argparser = ArgumentParser()
    argparser.add_argument("file", type=str)
    args = argparser.parse_args()

    print(pickle.load(open(args.file, "rb")))

